title: Anthony Frank
# logo
description: Artificial Intelligence Masters Student | Full Stack Engineer
contact:
  email: acmclarenfrank@gmail.com
  linkedin: linkedin.com/in/anthony-f-396056126
# show_downloads: true
theme: jekyll-theme-minimal
